### ISSUE TITLE
model mismatch

### ISSUE THREAD

**Issue by yallien** [VITA-Group/TransGAN#44]
Hi,thank u for your great work.But I got some problems when testing your provided model from https://drive.google.com/file/d/1Td9baoNua6jNtVvsnJczW1u4QWa1w9sl/view?usp=sharing.
It seemed that the network of trained model  is different from that in model_search.

**Comment by yueruchen** [comment]
Hi, could you please provide the error log?

**Comment by yallien** [comment]
Traceback (most recent call last):
  File "test.py", line 148, in <module>
    main()
  File "test.py", line 130, in main
    gen_net.load_state_dict(checkpoint['avg_gen_state_dict'])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.pos_embed_1: copying a param with shape torch.Size([1, 64, 1024]) from checkpoint, the shape in current model is torch.Size([1, 16, 64]).
	size mismatch for module.pos_embed_2: copying a param with shape torch.Size([1, 256, 256]) from checkpoint, the shape in current model is torch.Size([1, 64, 16]).
	size mismatch for module.pos_embed_3: copying a param with shape torch.Size([1, 1024, 64]) from checkpoint, the shape in current model is torch.Size([1, 256, 4]).
	size mismatch for module.l1.weight: copying a param with shape torch.Size([65536, 256]) from checkpoint, the shape in current model is torch.Size([1024, 128]).
	size mismatch for module.l1.bias: copying a param with shape torch.Size([65536]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for module.blocks.block.0.norm1.norm.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.blocks.block.0.norm1.norm.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.blocks.block.0.attn.relative_position_bias_table: copying a param with shape torch.Size([225, 4]) from checkpoint, the shape in current model is torch.Size([49, 4]).
	size mismatch for module.blocks.block.0.attn.relative_position_index: copying a param with shape torch.Size([64, 64]) from checkpoint, the shape in current model is torch.Size([16, 16]).
	size mismatch for module.blocks.block.0.attn.qkv.weight: copying a param with shape torch.Size([3072, 1024]) from checkpoint, the shape in current model is torch.Size([192, 64]).
	size mismatch for module.blocks.block.0.attn.proj.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([64, 64]).
	size mismatch for module.blocks.block.0.attn.proj.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.blocks.block.0.norm2.norm.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.blocks.block.0.norm2.norm.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for module.blocks.block.0.mlp.fc1.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([256, 64]).
	size mismatch for module.blocks.block.0.mlp.fc1.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for module.blocks.block.0.mlp.fc2.weight: copying a param with shape torch.Size([1024, 4096]) from checkpoint, the shape in current model is torch.Size([64, 256]).

python test.py --exp_name cifar_test --load_path ./checkpoint/cifar_checkpoint  --gen_model ViT_custom_rp
I also tried  other gen_model ,but the same.

**Comment by yueruchen** [comment]
`size mismatch for module.pos_embed_1: copying a param with shape torch.Size([1, 64, 1024]) from checkpoint, the shape in current model is torch.Size([1, 16, 64]).`

I guess this is becuase the dimension mismatch? What is the `gf_dim` in your command? The correct one should be 1024

**Comment by yallien** [comment]
Thanks! I forgot to change the parameter according to the train file
