### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by maoshen5** [VITA-Group/TransGAN#78]
I train this model and download cifar_checkpoint,but:
=> calculate fid score
  0%|                                                                                                                                                         | 0/3125 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1377, in _do_call
    return fn(*args)
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.UnimplementedError: 2 root error(s) found.
  (0) UNIMPLEMENTED: DNN library is not found.
         [[{{node FID_Inception_Net/conv/Conv2D}}]]
         [[FID_Inception_Net/pool_3/_3]]
  (1) UNIMPLEMENTED: DNN library is not found.
         [[{{node FID_Inception_Net/conv/Conv2D}}]]
0 successful operations.
0 derived errors ignored.
I try to reduce the batchsize,but it still no work

**Comment by yueruchen** [comment]
Just disable evaluation on the training job and launch another evaluation job would be ok
